export const SEED_QUESTIONS = [
  { text: "What's her star sign? (Bonus point if you know the birthday!)", answer: "Taurus (April 22)" },
  { text: "What's her favorite color?", answer: "Burgundy or dark green" },
  { text: "What's her coffee order?", answer: "Regular coffee with low fat milk" },
  { text: "What's her favorite movie?", answer: "Legally Blonde, Shawshank Redemption, Apollo 13, Just Mercy" },
  { text: "What are her favorite sports teams?", answer: "Warriors, 49ers, Cal Bears" },
  { text: "Who was her teenage celebrity crush?", answer: "Zac Efron, Justin Bieber, Zayn Malik" },
  { text: "Where did she go to law school?", answer: "Georgetown" },
  { text: "What's her drink of choice?", answer: "Red wine or vodka martini extra dirty" },
  { text: "What's her favorite fast food?", answer: "In-N-Out (half point for McDonald's)" },
  { text: "What's her favorite conspiracy theory?", answer: "HELEN KELLER IS A FRAUD" },
  { text: "What animal does she have an irrational fear of?", answer: "Cats" },
  { text: "What was her major in college?", answer: "Political science" },
  { text: "What's her favorite type of music?", answer: "2000s throwback (esp hip hop/rap)" },
  { text: "What food is she repulsed by?", answer: "Goat cheese, corn" },
  { text: "What's her least favorite holiday?", answer: "Halloween" },
  { text: "What kind of Indian is she?", answer: "Half Oriya, half Tamilian" },
  { text: "What type of law does she practice?", answer: "Securities litigation and white collar defense" },
];
